import requests
import json
import time
import random
from typing import List, Dict, Optional
from datetime import datetime
from pathlib import Path

class ReceptionistClient:
    """Client for interacting with the AI Receptionist API."""
    
    def __init__(self, base_url: str = "http://127.0.0.1:8000"):
        self.base_url = base_url
        self.session = requests.Session()
        self.session.headers.update({"Content-Type": "application/json"})
    
    def health_check(self) -> Dict:
        """Check if the API is healthy."""
        try:
            response = self.session.get(f"{self.base_url}/health")
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as e:
            print(f"❌ Health check failed: {e}")
            return {"status": "unhealthy", "error": str(e)}
    
    def process_call(self, caller_phone: str, speech_text: str, call_sid: str) -> Dict:
        print("Send a call to the AI Receptionist for processing.")
        payload = {
            "caller_phone": caller_phone,
            "speech_text": speech_text,
            "call_sid": call_sid
        }
        
        try:
            print(f"📞 Sending: {speech_text}")
            response = self.session.post(f"{self.base_url}/process-call", json=payload)
            response.raise_for_status()
            result = response.json()
            print(f"🤖 Response: {result.get('response', 'No response')}")
            print(f"📊 Intent: {result.get('intent', 'Unknown')}")
            print(f"👤 Caller Type: {result.get('caller_type', 'Unknown')}")
            print(f"⚡ Next Action: {result.get('next_action', 'None')}")
            print(f"❌ Error Message: {result.get('error', 'No error')}")
            print("-" * 50)
            return result
        except requests.exceptions.RequestException as e:
            print(f"❌ API call failed: {e}")
            return {"success": False, "error": str(e)}

class ConversationSimulator:
    """Simulates realistic conversations with the AI Receptionist."""
    
    def __init__(self, client: ReceptionistClient):
        self.client = client
        self.call_sid_counter = 1000
        # Ensure conversations directory exists
        self.conversations_dir = Path("simulated_conversations")
        self.conversations_dir.mkdir(exist_ok=True)

    def generate_call_sid(self) -> str:
        """Generate a unique call SID."""
        call_sid = f"CA{self.call_sid_counter:010d}"
        self.call_sid_counter += 1
        return call_sid
    
    def _save_conversation(self, scenario_name: str, caller_phone: str, call_sid: str, results: List[Dict]) -> None:
        """Save the full conversation as a Markdown file with timestamp."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_name = scenario_name.replace(" ", "_").lower()
        phone = caller_phone.replace("+", "").replace("-", "").replace(".", "")
        filename = f"{timestamp}_{safe_name}_{phone}.md"
        filepath = self.conversations_dir / filename

        md_lines = [
            f"# Conversation Log: {scenario_name}",
            "",
            f"- **Caller Phone:** {caller_phone}",
            f"- **Call SID:** {call_sid}",
            f"- **Timestamp:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "## Conversation",
            ""
        ]

        for turn in results:
            md_lines.append(f"### Turn {turn['turn']}")
            md_lines.append(f"**Caller:** {turn['input']}")
            outcome = turn["result"]
            md_lines.append(f"**AI Response:** {outcome.get('response','')}")
            md_lines.append(f"- Intent: {outcome.get('intent','Unknown')}")
            md_lines.append(f"- Caller Type: {outcome.get('caller_type','Unknown')}")
            md_lines.append(f"- Next Action: {outcome.get('next_action','None')}")
            md_lines.append("")

        md_lines.append("---")
        md_lines.append("*Generated by Conversation Simulator*")

        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(md_lines))

        print(f"📝 Conversation saved to {filepath}")

    def simulate_conversation(self, scenario: Dict) -> List[Dict]:
        """Simulate a multi-turn conversation based on a scenario."""
        caller_phone = scenario["caller_phone"]
        conversation = scenario["conversation"]
        call_sid = self.generate_call_sid()
        
        print(f"\n🎭 Starting scenario: {scenario['name']}")
        print(f"📱 Caller: {caller_phone}")
        print(f"🆔 Call SID: {call_sid}")
        print("=" * 60)
        
        results = []
        
        for turn_num, speech_text in enumerate(conversation, 1):
            print(f"\n--- Turn: {turn_num} ---")
            
            if turn_num > 1:
                delay = random.uniform(1, 3)
                print(f"⏳ Waiting {delay:.1f}s...")
                time.sleep(delay)
            
            result = self.client.process_call(caller_phone, speech_text, call_sid)
            results.append({
                "turn": turn_num,
                "input": speech_text,
                "result": result
            })

            if not result.get("success", False):
                print("❌ Conversation stopped due to error")
                break
            break

        # Save conversation log
        self._save_conversation(scenario["name"], caller_phone, call_sid, results)
        
        return results

def main():
    client = ReceptionistClient()
    
    print("🏥 Checking API health...")
    health = client.health_check()
    print(f"Health status: {health}")
    
    if health.get("status") != "healthy":
        print("❌ API is not healthy. Exiting.")
        return
    
    simulator = ConversationSimulator(client)
    
     # Define conversation scenarios
    scenarios = [
        {
            "name": "Appointment Scheduling",
            "caller_phone": "+13388582100",
            "conversation": [
                "Hi, I want to schedule an appointment for next week."
            ],
        },
        {
            "name": "Appointment Scheduling",
            "caller_phone": "+13388582100",
            "conversation": [
                "Hi, I want to schedule an appointment for next week.",
                "I'm available Tuesday or Wednesday afternoon.",
                "Tuesday at 2 PM works great for me.",
                "Thank you, see you then!"
            ]
        },
        {
            "name": "Billing Inquiry",
            "caller_phone": "+14155555678",
            "conversation": [
                "I have a question about my invoice.",
                "I was charged twice for the same service last month.",
                "The invoice number is INV-2024-001234.",
                "Yes, please transfer me to billing department."
            ]
        },
        {
            "name": "General Information",
            "caller_phone": "+14155559999",
            "conversation": [
                "What are your business hours?",
                "Do you offer weekend appointments?",
                "How much does a consultation cost?",
                "Thank you for the information."
            ]
        },
        {
            "name": "Vendor Business Hours Change",
            "caller_phone": "+1863.888.1787",
            "conversation": [
                "I need to change my business hours for next week monday to friday to Closed.",
                "Please verify my business hours for next week",
                "Thank you."
            ]
        },
        
        {
            "name": "Emergency Call",
            "caller_phone": "+14155551111",
            "conversation": [
                "This is an emergency! I need help immediately!",
                "My system is down and I have a presentation in 30 minutes!",
                "Yes, please connect me to technical support right away."
            ]
        },
        {
            "name": "Spam/Sales Call",
            "caller_phone": "+18005551234",
            "conversation": [
                "Hello, I'm calling about your car's extended warranty.",
                "We have a special offer just for you today.",
                "This offer expires in the next 10 minutes."
            ]
        }
    ]
    
    all_results = []
    
    for scenario in scenarios:
        try:
            results = simulator.simulate_conversation(scenario)
            all_results.append({"scenario": scenario["name"], "results": results})
            time.sleep(2)
        except Exception as e:
            print(f"❌ Error in scenario '{scenario['name']}': {e}")
            continue
        break
    
    print("\n🏁 Simulation complete!")

if __name__ == "__main__":
    main()